### GET
GET http://localhost:8080/products

###

### POST
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "Dell",
  "quantity": 10,
  "price": 3000
}
###POST


